### ISSUE TITLE
Ubuntu ablestack dpkg error

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/cockpit-plugin-ablestack#1]
Build environment : Ubuntu 20.04 server

배포 패키지 설치 후 실행되는 postinst 스크립트 실행 중 오류

![캡처](https://user-images.githubusercontent.com/70362526/106551363-6cb10500-6558-11eb-8a11-1448a3c7c892.PNG)

* debian/postinst 스크립트에 #dpkg 또는 #apt-get 명령어 실행 시 위와 같은 오류가 발생하며, 스크립트에 설치 명령어 제외한 후에 다시 패키징하여 설치하면 정상적으로 스크립트 실행되고 패키지가 설치된다.

[ debian 경로에 하위 파일 ]

- control 파일

![control](https://user-images.githubusercontent.com/70362526/106553023-d7b00b00-655b-11eb-9474-2b987eabc3de.PNG)

- postinst 파일

![postinst](https://user-images.githubusercontent.com/70362526/106553030-db439200-655b-11eb-8014-24c01a35ca4f.PNG)

**Comment by dhslove** [comment]
RPM, DEB 등의 패키지 설치 시, Postinst 단계에서 의존성 패키지를 설치하는 작업을 하지 말고, 각각의 패키지를 따로 따로 설치하도록 설계해야 합니다

**Comment by leca777** [comment]
> Build environment : Ubuntu 20.04 server
> 
> 배포 패키지 설치 후 실행되는 postinst 스크립트 실행 중 오류
> 
> ![캡처](https://user-images.githubusercontent.com/70362526/106551363-6cb10500-6558-11eb-8a11-1448a3c7c892.PNG)
> 
> * debian/postinst 스크립트에 #dpkg 또는 #apt-get 명령어 실행 시 위와 같은 오류가 발생하며, 스크립트에 설치 명령어 제외한 후에 다시 패키징하여 설치하면 정상적으로 스크립트 실행되고 패키지가 설치된다.
> 
> [ debian 경로에 하위 파일 ]
> 
> * control 파일
> 
> ![control](https://user-images.githubusercontent.com/70362526/106553023-d7b00b00-655b-11eb-9474-2b987eabc3de.PNG)
> 
> * postinst 파일
> 
> ![postinst](https://user-images.githubusercontent.com/70362526/106553030-db439200-655b-11eb-8014-24c01a35ca4f.PNG)

**Comment by Dajeong-Park** [comment]
패키지 빌드 시 의존성 패키지 설치 작업을 제외하고 별도로 설치하도록 설계를 변경하였으며, Ubuntu control 파일의 Depends와 CentOS spec 파일의 Requires 항목에 cockpit 의존성 패키지를 추가하였습니다.
