### ISSUE TITLE
네트워크 NIC 디바이스 정보 조회

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/cockpit-plugin-ablestack#41]
# 개발 개요
스토리지센터 가상머신에 사용할 NIC Passthrough 조회하여 화면을 구성
## 개발 기능
- NIC Passthrough 정보 조회
- NIC Passthrough 목록 생성
## 기타

#7(개발기능목록)

**Comment by ycyun** [comment]
제가 하겠습니다.
