### ISSUE TITLE
파이선 개발 표준 정의

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/cockpit-plugin-ablestack#59]
백엔드 개발을 위한 파이선 개발 표준을 정의
* 파일의 경로 및 위치
* 파일의 명명 규칙
* 파일의 기본 구성(명명규칙, 주석등)
* 적용 가이드 및 샘플 코드
* 기타 표준과 관련된 정의 사항

_개발 표준을 정의하고 향 후 개발표준 문서(WIKI)에 등재_

**Comment by ycyun** [comment]
제가 하겠습니다.
