### ISSUE TITLE
라이선스 문서가 필요할것 같습니다.

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/cockpit-plugin-ablestack#61]
**Is your feature request related to a problem? Please describe.**
현재 라이선스를 정의한 LICENSE 파일이 없습니다.

**Describe the solution you'd like**
오픈소스 프로젝트의 플러그인을 개발중이므로, cockpit의 라이선스정책을 확인하고 필요하다면 cockpit의 라이선스를 따르거나 이 플러그인의 라이선스를 수립해야 합니다.

**Comment by leca777** [comment]
ablestack의 라이선스는 일반 상용라이선스 정책을 적용하며 
ablestack에 대한 구성요소(OSS)에 대한 라이선스 정책은 다음과 같습니다 

* 스토리지 : CEPH - LGPL
* 하이퍼바이저 : CentOS 8 KVM - GPL v2, LGPL v2
* 관리플랫폼 : Apache CloudStack - Apache License 2.0
* 관리데이터베이스 : MySQL - GPL v2
* 모니터링데이터베이스  : InfluxDB - MIT
* 모니터링 자동화 : Prometheus/Alert Manager - Apache License 2.0
* 대시보드 시각화 : Grafana -  Apache License 2.0
* UI 플랫폼 : Vue.js -  MIT
* 배포자동화 도구 : Cockpit - LGPL v2
