### ISSUE TITLE
스토리지 테스트환경을 위한 ceph 설치 및 구성

### ISSUE THREAD

**Issue by jschoiRR** [ablecloud-team/cockpit-plugin-ablestack#79]
스토리지 클러스터 상태 조회 및 상태 조작을 위한 테스트 환경이 필요함.

- ceph -s 및 유지보수 모드 설정 테스트
- 스토리지센터 클러스터 구성여부 확인 등

#77

**Comment by jschoiRR** [comment]
#

**Comment by kt-cheon** [comment]
@kt-cheon  제가 구성하겠습니다.

**Comment by kt-cheon** [comment]
ceph pacific 구성 정보
host : 10.10.1.1, 10.10.1.2, 10.10.1.3 (ablecloud1, ablecloud2, ablecloud3)
scvm : 10.10.1.11, 10.10.1.12, 10.10.1.13 (scvm1, scvm2, scvm3)

cpeh dashboard : https://{(현재 mgr이 실행중인 scvm ip}:8443   (예,https://10.10.1.11:8443)
id : admin / pw : Ablecloud1!

**Comment by kt-cheon** [comment]
위 6개 이외의 VM (예를 들어 개발 VM)에서 구성되어 있는 ceph 정보를 확인 하고 싶을 때,

1.  /etc/yum.repos.d/ceph.repo 파일을 생성하고 아래 값을 입력 후 저장합니다.

 > vi /etc/yum.repos.d/ceph.repo

[ceph]
name=Ceph packages for $basearch
baseurl=https://download.ceph.com/rpm-pacific/el8/$basearch
enabled=1
priority=2
gpgcheck=1
gpgkey=https://download.ceph.com/keys/release.asc

[ceph-noarch]
name=Ceph noarch packages
baseurl=https://download.ceph.com/rpm-pacific/el8/noarch
enabled=1
priority=2
gpgcheck=1
gpgkey=https://download.ceph.com/keys/release.asc

[ceph-source]
name=Ceph source packages
baseurl=https://download.ceph.com/rpm-pacific/el8/SRPMS
enabled=0
priority=2
gpgcheck=1
gpgkey=https://download.ceph.com/keys/release.asc

2. ceph install
 > dnf install ceph

3. ceph key 파일을 복사
 > scp scvm:/etc/ceph/* {개발 vm}:/etc/ceph/

4. 개발 vm에서 ceph -s 를 입력하면 ceph 구성 정보를 확인 할 수 있습니다.

**Comment by kt-cheon** [comment]
해당 이슈를 완료 했습니다.
