### ISSUE TITLE
Kickstart Repository가 필요합니다.

### ISSUE THREAD

**Issue by kt-cheon** [ablecloud-team/cockpit-plugin-ablestack#83]
Kickstart 관련 repository 별도로 필요할 것 같습니다.

**Comment by kt-cheon** [comment]
kickstart repo와 cockpit plugin repo의 관리 방법도 필요할 것 같습니다.

**Comment by leca777** [comment]
ablestack-kickstart repository를 생성하였으니 해당 repository를 사용하면 됩니다
